AKS recommendation updates
Azure/review-checklists pull request #110
Opened 2022-01-25 08:48 UTC by infosatheesh2020

closes #96

2022-01-25 16:20 UTC, erjosito commented
Fixes #96

2022-01-28 13:54 UTC, erjosito requested changes

2022-01-29 03:16 UTC, infosatheesh2020 commented on checklists/aks_checklist.en.json
> +      "text": "If using Azure Disks and AZs, consider having nodepools within a zone for LRS disk or use ZRS disk for nodepools spanning multiple zones",
@erjosito Thanks. I added it back specific to LRS where it makes sense.

2022-02-02 17:01 UTC, erjosito approved these changes

2022-02-02 17:01 UTC, merged