Added 7 Graph queries to APIM checklist
Azure/review-checklists pull request #914
Opened 2024-09-20 19:06 UTC by seenu433

Added 7 Graph queries to APIM checklist

2024-09-20 19:20 UTC, andredewes reviewed
@seenu433 Shouldn't it be better for the recommendations that are only available in Premium instances that ARG queries filter only for sku == Premium?

For example, for customers that have Developer/Basic/Standard tiers they will be flagged in the recommendations about multi regional and AZ even though that's not possible.

2024-09-22 00:24 UTC, seenu433 commented
@andredewes - Unlike Advisor recommendations (for blast radius reasons), I would rather flag all instances in scope against compliance as we do not know the criticality of the workload.

2024-09-23 06:39 UTC, erjosito commented
You probably need to use single quotes in the ARG queries, otherwise the JSON is not valid

2024-09-26 08:14 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = ( sku.name == "Premium" and  isnotnull(properties.additionalLocations)) | distinct id, compliant
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito requested changes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = ( sku.name == "Premium" and  isnotnull(zones) and sku.capacity >= 2 ) | distinct id, compliant",
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = ( sku.name == "Premium" and  isnotnull(properties.additionalLocations)) | distinct id, compliant
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | join kind = leftouter (resources | where type == "microsoft.insights/autoscalesettings" | extend targetResourceUri
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = (isnotnull(properties.virtualNetworkConfiguration)) | distinct id, compliant",
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = (properties.virtualNetworkType == "None" and isnotnull(properties.privateEndpointConnections)) |
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = (properties.virtualNetworkType == "Internal") | distinct id, compliant",
Double quotes in the query string break the JSON syntax, please use single quotes

2024-09-26 08:15 UTC, erjosito commented on checklists/apim_checklist.en.json
> +            "graph": "resources | where type == "microsoft.apimanagement/service" | extend compliant = (isnotnull(identity)) | distinct id, compliant",
Double quotes in the query string break the JSON syntax, please use single quotes

2024-10-17 13:54 UTC, seenu433 commented
@erjosito -comments addressed.

2024-10-23 08:45 UTC, erjosito approved these changes

2024-10-23 08:45 UTC, merged