Naigaras sap6 arg
Azure/review-checklists pull request #938
Opened 2024-09-30 07:50 UTC by NaokiIgarashi

## Description
As part of our Hackathon 2024 activities, we added 20 ARG queries to the SAP checklist.

## Related Issue
non

## Checklist

- [x] I've tested my changes to ensure they are ready for review.
- [x] I've read the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) guide.
- [ ] I've updated the documentation (if applicable).
- [x ] Resource Graph queries have been included (and tested) for recommendations where ever possible[^note].
- [ ] Resource Graph queries have NOT been included (please explain below).

## Additional Information
Lines 613 and 1140 are highlighted (red), but there were no problems with the execution results of the query itself.

## Reviewer Notes
Is there a specific area you’d like feedback on? Please highlight it here. We're here to help and learn together! 💡
[review_checklist (SAP)_nonmacro_Naoki+Syed.xlsx](https://github.com/user-attachments/files/17185993/review_checklist.SAP._nonmacro_Naoki%2BSyed.xlsx)

[^note]:
    Details on how to add Azure Resource Graph queries to recommendations can be found [here](../blob/main/CONTRIBUTING.md#1-adding-or-modifying-resource-graph-queries).

2024-09-30 08:30 UTC, erjosito requested changes

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "resources | where type == 'microsoft.network/virtualnetworks' | extend addressSpace = todynamic(properties.addressSpace) | extend addressPrefix = todynamic(properties.addressSpa
It would be great if you could replace the `==` to `=~` to be case-insensitive

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "QuotaResources | where type =~ "microsoft.compute/locations/usages" | where subscriptionId in~ ("<Subscription1>","<Subscription2>") | mv-expand json = properties.value limit 40
You need to replace the double quotes (`"`) inside of the query by single quotes (`'`), othewise the JSON breaks.

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "resources | where type == 'microsoft.network/virtualnetworks' | mvexpand properties.virtualNetworkPeerings | project id, peeringName=properties_virtualNetworkPeerings.name, comp
It would be great if you could replace the `==` to `=~` to be case-insensitive

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "resources | where type=='microsoft.network/virtualhubs' | extend compliant = isnotnull(properties.azureFirewall.id) | project id, compliant"
It would be great if you could replace the `==` to `=~` to be case-insensitive

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "Resources | where type =~ "Microsoft.Network/NetworkInterfaces" | where properties.enableAcceleratedNetworking == "false" | project name, subscriptionId, properties.enableAccele
You need to replace the double quotes (`"`) inside of the query by single quotes (`'`), othewise the JSON breaks.

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "Resources | join kind=leftouter (ResourceContainers | where type=='microsoft.resources/subscriptions' | project SubName=name, subscriptionId) on subscriptionId | where type == '
It would be great if you could replace the `==` to `=~` to be case-insensitive

2024-09-30 08:30 UTC, erjosito commented on checklists/sap_checklist.en.json
> +            "graph": "Resources | join kind=leftouter (ResourceContainers | where type=='microsoft.resources/subscriptions' | project SubName=name, subscriptionId) on subscriptionId | where type == '
It would be great if you could replace the `==` to `=~` to be case-insensitive

2024-10-01 01:15 UTC, NaokiIgarashi commented
Hello @erjosito !
Thank you for pointing that out!
I've corrected all the things you pointed out, but there are still many == cases remaining. Would it be better to change them all to =~?

2024-10-01 07:24 UTC, erjosito approved these changes

2024-10-01 07:26 UTC, erjosito commented
I would suggest to do that. By using `=~` your queries will be more solid, in case the PG changes the casing of provider names or property keys or values.

2024-10-02 01:52 UTC, NaokiIgarashi commented
Hey @erjosito ,

i modified all the character from == to =~ .
please check it!

2024-10-02 08:27 UTC, erjosito approved these changes

2024-10-02 08:28 UTC, erjosito commented
Fantastic thanks a lot @NaokiIgarashi !

2024-10-02 08:28 UTC, merged